FROM python:3.9-bullseye

USER root

SHELL ["/bin/bash", "-c"]

RUN mkdir $HOME/.venv

RUN python -m  venv $HOME/.venv/dvt 
RUN source $HOME/.venv/dvt/bin/activate \
    && pip install google-pso-data-validator
